[package]
name = "day-15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.26.0"
intersect2d = "0.4.2"
itertools = "0.11.0"
nom = "7.1.3"
regex = "1.10.2"
